### PR TITLE
Mu 24

### PR DESCRIPTION
**Pull request by Staroz**
Please review this PR.

### CODE REVIEW

**Review by sphinix27 — CHANGES_REQUESTED** [review]
Looks good.
Please add the commands used to run the tests inside DockerFile and I'll approve.

**Comment by Staroz** [comment]
Sorry maybe this is not what you asked for, I think that you need the commands of the docker-compose file, into runs two services, Playwright and Cypress services.
The commands of Playwright are 1. npm install and 2. npx playwright test. 
The other one waits for PLaywright services to finish and then it does 1. npm install 2. npx cypress run.
I will be attentive to your comments. Thanks.

**Comment by sphinix27** [comment]
I just want some docs in readme on how to run tests locally with the docker image

**Review by sphinix27 — APPROVED** [review]
LGTM

**Pull request merged**
